### ISSUE TITLE
return within qc::perm_if does not work

### ISSUE THREAD

**Issue by PeterChaplin** [qcode-software/qcode-tcl#245] opened 2015-07-14 08:46 UTC
```tcl
qc::perm_if {
set foo bar
return
}
set bar baz
```
Would expect variable bar not to be set.

**Comment by nicky-johnstone** [comment] 2015-07-14 10:15
```tcl
qc::perm_if perm method {
    set foo bar
    return -code return
}
set bar baz
```
should do the trick or perhaps more readable might be `return -level 2`. They are equivalent.

If we don't want to this burden to be on the developer then the only way I can think to try and account for the caller's intentions would be along the lines of:

```tcl
proc qc::perm_if { perm_name method if_code {. else} {else_code ""} } {
    #| Evaluate if_code if current user has permission else else_code
    set code ""
    if { [perm_test $perm_name $method] } {
        set code $if_code
    } elseif { $else_code ne "" } {
        set code $else_code
    }

    if { $code ne "" } {
        try {
            uplevel 1 $code
        }  on error [list result options] - \
        on ok [list result options] - \
        on break [list result options] - \
        on continue [list result options] - \
        on return [list result options] {
            dict incr options -level
            return -options $options $result
        }
    }
}
```

The above code should definitely work for `return` but would require thorough testing on other return codes and levels to make sure everything functions as expected.

**Comment by bvw** [comment] 2015-07-14 10:21
The later idea please.
qc::perm_if should work as naturally as possible.

**Comment by nicky-johnstone** [comment] 2015-07-14 13:34
#246 

This should make the `qc::perm_if` code blocks function just like a tcl `if` statement.

@PeterChaplin Could you check if the problem is now resolved with the particular case that you had encountered?

**Comment by PeterChaplin** [comment] 2015-07-14 13:54
Yes, that seems to fix it.

**Closed** 2015-07-14 13:57 UTC
